#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from backend.app.admin.model.sys_api import Api
from backend.app.admin.model.sys_casbin_rule import CasbinRule
from backend.app.admin.model.sys_config import Config
from backend.app.admin.model.sys_dept import Dept
from backend.app.admin.model.sys_dict_data import DictData
from backend.app.admin.model.sys_dict_type import DictType
from backend.app.admin.model.sys_login_log import LoginLog
from backend.app.admin.model.sys_menu import Menu
from backend.app.admin.model.sys_opera_log import OperaLog
from backend.app.admin.model.sys_role import Role
from backend.app.admin.model.sys_doc import SysDoc
from backend.app.admin.model.sys_doc_data import SysDocData
from backend.app.admin.model.sys_doc_chunk import SysDocChunk
from backend.app.admin.model.sys_doc_embedding import SysDocEmbedding
from backend.app.admin.model.sys_user import User
from backend.app.admin.model.sys_user_social import UserSocial
from backend.app.admin.model.sys_org import SysOrg
from backend.app.admin.model.sys_assets import SysAssets
from backend.app.admin.model.sys_event import Event
from backend.app.admin.model.sys_tag import Tag
from backend.app.admin.model.mail_attachment import MailAttachment
from backend.app.admin.model.mail_msg import MailMsg
from backend.app.admin.model.mail_box import MailBox
from backend.app.admin.model.social_account_post import SocialAccountPost
from backend.app.admin.model.social_account import SocialAccount
from backend.app.admin.model.sys_person import Person
from backend.app.admin.model.sys_person_relation import PersonRelation
from backend.app.admin.model.sys_news import News
from backend.app.admin.model.sys_subject import Subject
from backend.app.admin.model.sys_scandal import Scandal