#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from backend.app.admin.model.sys_api import Api
from backend.app.admin.model.sys_casbin_rule import CasbinRule
from backend.app.admin.model.sys_config import Config
from backend.app.admin.model.sys_dept import Dept
from backend.app.admin.model.sys_dict_data import DictData
from backend.app.admin.model.sys_dict_type import DictType
from backend.app.admin.model.sys_login_log import LoginLog
from backend.app.admin.model.sys_menu import Menu
from backend.app.admin.model.sys_opera_log import OperaLog
from backend.app.admin.model.sys_role import Role
from backend.app.admin.model.sys_doc import SysDoc
from backend.app.admin.model.sys_doc_dir import SysDocDir
from backend.app.admin.model.sys_doc_data import SysDocData
from backend.app.admin.model.sys_doc_embedding import SysDocEmbedding
from backend.app.admin.model.sys_user import User
from backend.app.admin.model.sys_user_social import UserSocial
from backend.app.admin.model.sys_tag import Tag
from backend.app.admin.model.mail_msg import MailMsg
from backend.app.admin.model.mail_box import MailBox
from backend.app.admin.model.sys_entity import Entity
from backend.app.admin.model.sys_star_collect import StarCollect
from backend.app.admin.model.sys_entity_relationship import EntityRelation
from backend.app.admin.model.sys_subject_predict_object import SubjectPredictObject
from backend.app.admin.model.sys_upload_task import UploadTask
from backend.app.admin.model.sys_chat_session import ChatSession
from backend.app.admin.model.sys_chat_message import ChatMessage
from backend.app.admin.model.sys_rss_source import RssSource
from backend.app.admin.model.sys_briefing import Briefing