version: "3.10"

networks:
  fba_network:
    name: fba_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24

volumes:
  fba_pg:
    name: fba_pg
  fba_redis:
    name: fba_redis
  fba_static:
    name: fba_static
  fba-minio:
    name: fba-minio
  fba_rabbitmq:
    name: fba_rabbitmq

services:
  fba_server:
    build:
      context: ../../../
      dockerfile: backend/backend.dockerfile
    image: fba_server:latest
    ports:
      - "8001:8001"
    container_name: fba_server
    restart: always
    depends_on:
      - fba_pg
      - fba_redis
      - fba-minio
      # - fba_celery
    volumes:
      - fba_static:/fba/backend/app/static
    networks:
      - fba_network
    environment:
      - LLM_MODEL=Qwen2.5-7B-Instruct
      - LLM_API_URL=http://172.17.0.1:8103/v1/chat/completions
      - LLM_API_KEY=
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_URL=http://172.17.0.1:8104/text_to_vector
      - EMBEDDING_API_KEY=
      - OCR_URL=http://172.17.0.1:8120/predict
    command:
      - bash
      - -c
      - |
        wait-for-it -s fba_pg:5432 -s fba_redis:6379 -t 300
        mkdir -p /var/log/supervisor/
        rm -f /fba/backend/gunicorn.pid
        supervisord -c /fba/deploy/backend/supervisor.conf
        supervisorctl restart fastapi_server

  fba_pg:
    image: paradedb/paradedb:0.15.20-pg16
    container_name: fba_pg
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - fba_pg:/var/lib/postgresql/data/
    networks:
      - fba_network
    environment:
      - PGDATA=/var/lib/postgresql/data/
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fba


  fba_redis:
    image: redis:6.2.7
    ports:
      - "${DOCKER_REDIS_MAP_PORT:-6379}:6379"
    container_name: fba_redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - fba_redis:/data
    networks:
      - fba_network


  fba_ui:
    image: fba_ui:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: fba_ui
    restart: always
    command:
      - nginx
      - -g
      - daemon off;
    volumes:
      # nginx https conf
      # When deploying through docker, you need to open this configuration item and
      # ensure that the docker_ssl path is consistent with that in nginx conf
      # - local_ssl_pem_path:/etc/ssl/xxx.pem
      # - local_ssl_key_path:/etc/ssl/xxx.key
      - fba_static:/www/fba_server/backend/static
    networks:
      - fba_network


  # quay.io/minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
  fba-minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: fba-minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - fba-minio:/data
    networks:
      - fba_network
    command:
      - server
      - /data
      - --console-address=0.0.0.0:9001